name: Reto Scherrer
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40552
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bbc7c7'
    - '#305e6d'
    - '#022a44'
    - '#727d83'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
